-- ATLAS - Autenticación LOCAL/LDAP compatible con tablas comprimidas.
-- No modifica GT_USUARIO.
-- Ejecutar una sola vez.

CREATE TABLE GT_USUARIO_AUTH (
    ID_USUARIO           NUMBER NOT NULL,
    TIPO_AUTENTICACION   VARCHAR2(10 CHAR) DEFAULT 'LOCAL' NOT NULL,
    USUARIO_LDAP         VARCHAR2(200 CHAR),
    USUARIO_LDAP_NORM    VARCHAR2(200 CHAR)
        GENERATED ALWAYS AS (UPPER(TRIM(USUARIO_LDAP))) VIRTUAL,
    ULTIMO_LOGIN_EXITO   TIMESTAMP,
    ULTIMO_LOGIN_FALLIDO TIMESTAMP,
    INTENTOS_FALLIDOS    NUMBER DEFAULT 0 NOT NULL,
    BLOQUEADO_HASTA      TIMESTAMP,
    SESSION_VERSION      NUMBER DEFAULT 1 NOT NULL,
    FECHA_CREACION       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION  TIMESTAMP,
    CONSTRAINT PK_GT_USUARIO_AUTH PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_GT_USUARIO_AUTH_USU FOREIGN KEY (ID_USUARIO)
        REFERENCES GT_USUARIO (ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT CK_GT_USUARIO_AUTH_TIPO CHECK (TIPO_AUTENTICACION IN ('LOCAL', 'LDAP')),
    CONSTRAINT CK_GT_USUARIO_AUTH_INT CHECK (INTENTOS_FALLIDOS >= 0),
    CONSTRAINT CK_GT_USUARIO_AUTH_LDAP CHECK (
        TIPO_AUTENTICACION = 'LOCAL'
        OR (TIPO_AUTENTICACION = 'LDAP' AND USUARIO_LDAP IS NOT NULL)
    )
) NOCOMPRESS;

CREATE UNIQUE INDEX UK_GT_USUARIO_AUTH_LDAP
    ON GT_USUARIO_AUTH (USUARIO_LDAP_NORM);

MERGE INTO GT_USUARIO_AUTH A
USING (SELECT ID_USUARIO FROM GT_USUARIO) U
ON (A.ID_USUARIO = U.ID_USUARIO)
WHEN NOT MATCHED THEN
    INSERT (ID_USUARIO, TIPO_AUTENTICACION, USUARIO_LDAP, INTENTOS_FALLIDOS)
    VALUES (U.ID_USUARIO, 'LOCAL', NULL, 0);

COMMIT;
