/* ============================================================
   ATLAS S.2.0 - VALIDACION ORACLE GREENFIELD
   Ejecutar despues del instalador greenfield.
   Compatible con DBeaver.
   ============================================================ */

SELECT 'TABLE' CONTROL, COUNT(*) REAL, 30 ESPERADO,
       CASE WHEN COUNT(*)=30 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TABLES WHERE TABLE_NAME LIKE 'GT\_%' ESCAPE '\'
UNION ALL
SELECT 'VIEW', COUNT(*), 9, CASE WHEN COUNT(*)=9 THEN 'OK' ELSE 'REVISAR' END
FROM USER_VIEWS WHERE VIEW_NAME LIKE 'VW\_GT\_%' ESCAPE '\'
UNION ALL
SELECT 'PACKAGE_SPEC', COUNT(*), 3, CASE WHEN COUNT(*)=3 THEN 'OK' ELSE 'REVISAR' END
FROM USER_OBJECTS WHERE OBJECT_TYPE='PACKAGE' AND OBJECT_NAME LIKE 'PKG\_GT\_%' ESCAPE '\'
UNION ALL
SELECT 'PACKAGE_BODY', COUNT(*), 3, CASE WHEN COUNT(*)=3 THEN 'OK' ELSE 'REVISAR' END
FROM USER_OBJECTS WHERE OBJECT_TYPE='PACKAGE BODY' AND OBJECT_NAME LIKE 'PKG\_GT\_%' ESCAPE '\';

SELECT CONSTRAINT_TYPE, COUNT(*) REAL,
       CASE CONSTRAINT_TYPE WHEN 'C' THEN 311 WHEN 'P' THEN 30 WHEN 'R' THEN 50 WHEN 'U' THEN 20 END ESPERADO,
       CASE
         WHEN CONSTRAINT_TYPE='C' AND COUNT(*)=311 THEN 'OK'
         WHEN CONSTRAINT_TYPE='P' AND COUNT(*)=30 THEN 'OK'
         WHEN CONSTRAINT_TYPE='R' AND COUNT(*)=50 THEN 'OK'
         WHEN CONSTRAINT_TYPE='U' AND COUNT(*)=20 THEN 'OK'
         ELSE 'REVISAR'
       END ESTADO
FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'GT\_%' ESCAPE '\' AND CONSTRAINT_TYPE IN ('C','P','R','U')
GROUP BY CONSTRAINT_TYPE ORDER BY CONSTRAINT_TYPE;

SELECT 'INDICES_ATLAS_NO_SYS' CONTROL, COUNT(*) REAL, 77 ESPERADO,
       CASE WHEN COUNT(*)=77 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_INDEXES
WHERE TABLE_NAME LIKE 'GT\_%' ESCAPE '\'
  AND INDEX_NAME NOT LIKE 'SYS_%';

SELECT 'GT_ROL' CATALOGO, COUNT(*) REAL, 4 ESPERADO, CASE WHEN COUNT(*)=4 THEN 'OK' ELSE 'REVISAR' END ESTADO FROM GT_ROL
UNION ALL SELECT 'GT_PERMISO', COUNT(*), 2, CASE WHEN COUNT(*)=2 THEN 'OK' ELSE 'REVISAR' END FROM GT_PERMISO
UNION ALL SELECT 'GT_MODALIDAD_DIA', COUNT(*), 12, CASE WHEN COUNT(*)=12 THEN 'OK' ELSE 'REVISAR' END FROM GT_MODALIDAD_DIA
UNION ALL SELECT 'GT_PARAMETRO', COUNT(*), 3, CASE WHEN COUNT(*)=3 THEN 'OK' ELSE 'REVISAR' END FROM GT_PARAMETRO
UNION ALL SELECT 'GT_PARAMETRO_SCORE', COUNT(*), 18, CASE WHEN COUNT(*)=18 THEN 'OK' ELSE 'REVISAR' END FROM GT_PARAMETRO_SCORE
UNION ALL SELECT 'GT_CATEGORIA_COSTO', COUNT(*), 5, CASE WHEN COUNT(*)=5 THEN 'OK' ELSE 'REVISAR' END FROM GT_CATEGORIA_COSTO;

SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
FROM USER_OBJECTS
WHERE (OBJECT_NAME LIKE 'GT\_%' ESCAPE '\'
    OR OBJECT_NAME LIKE 'VW\_GT\_%' ESCAPE '\'
    OR OBJECT_NAME LIKE 'PKG\_GT\_%' ESCAPE '\')
  AND STATUS <> 'VALID'
ORDER BY OBJECT_TYPE, OBJECT_NAME;

SELECT NAME, TYPE, LINE, POSITION, TEXT
FROM USER_ERRORS
WHERE NAME LIKE 'PKG\_GT\_%' ESCAPE '\'
   OR NAME LIKE 'VW\_GT\_%' ESCAPE '\'
ORDER BY NAME, TYPE, SEQUENCE;

SELECT 'ORIGENES_BLOQUEADOS' CONTROL, COUNT(*) CANTIDAD
FROM GT_LOGIN_RATE_LIMIT
WHERE BLOQUEADO_HASTA > SYSTIMESTAMP;
