/* ATLAS S.2.0 - ROLLBACK GREENFIELD
   DESTRUCTIVO. Usar solo en un esquema greenfield de prueba. */

DROP PACKAGE PKG_GT_ORG_UNIDAD;
DROP PACKAGE PKG_GT_IMPUTACION;
DROP PACKAGE PKG_GT_COSTOS;

DROP VIEW VW_GT_HORAS_OPEX_CAPEX;
DROP VIEW VW_GT_UNIDAD_JERARQUIA;
DROP VIEW VW_GT_TAREA_IMPUTABLE_HOY;
DROP VIEW VW_GT_SCORE_PRIORIDAD;
DROP VIEW VW_GT_IMPUTACION_DETALLE;
DROP VIEW VW_GT_COSTO_CENTRO_MES;
DROP VIEW VW_GT_COSTO_ACTIVIDAD_MES;
DROP VIEW VW_GT_CARGA_DIARIA_ALERTA;
DROP VIEW VW_GT_CAPACIDAD_SEMANAL;

DROP TABLE GT_TAREA_ASIGNACION CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_TAREA_ACTIVIDAD CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_IMPUTACION_HORAS CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_COSTO_IMPUTACION_MES CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_ALERTA CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_TAREA CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_VALIDACION_PERIODO CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_USUARIO_UNIDAD CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_USUARIO_PERMISO CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_USUARIO_COSTO CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_USUARIO_AUTH CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_RESULTADO_ACT_MES CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_PROYECTO CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_EVAL_AUTOMATIZACION CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_COSTO_CATEGORIA_MES CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_CALENDARIO_PERSONA CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_AUDITORIA CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_ACTIVIDAD_CC CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_SCORE_ACTIVIDAD_MES CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_USUARIO CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_ACTIVIDAD CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_ROL CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_PERMISO CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_PARAMETRO_SCORE CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_PARAMETRO CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_ORG_UNIDAD CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_MODALIDAD_DIA CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_LOGIN_RATE_LIMIT CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_CENTRO_COSTO CASCADE CONSTRAINTS PURGE;
DROP TABLE GT_CATEGORIA_COSTO CASCADE CONSTRAINTS PURGE;
