/*
ATLAS - VALIDACIÓN IMPUTACIÓN DIRECTA A PROYECTOS V3
*/

SELECT
    P.ID_PROYECTO,
    P.CODIGO AS PROYECTO,
    P.NOMBRE,
    P.ACTIVO AS PROYECTO_ACTIVO,
    P.PERMITE_IMPUTACION AS PROYECTO_PERMITE,
    T.ID_TAREA,
    T.CODIGO AS TAREA_TECNICA,
    T.ACTIVO AS TAREA_ACTIVA,
    T.PERMITE_IMPUTACION AS TAREA_PERMITE,
    CASE
        WHEN T.ID_PROYECTO IS NOT NULL
         AND T.CODIGO = 'PRYGEN_' || TO_CHAR(T.ID_PROYECTO)
        THEN 'S'
        ELSE 'N'
    END AS ES_TAREA_PROYECTO
FROM GT_PROYECTO P
LEFT JOIN GT_TAREA T
  ON T.ID_PROYECTO = P.ID_PROYECTO
 AND T.CODIGO = 'PRYGEN_' || TO_CHAR(P.ID_PROYECTO)
ORDER BY P.CODIGO;

SELECT
    COUNT(*) AS PROYECTOS_SIN_TAREA_TECNICA
FROM GT_PROYECTO P
WHERE NOT EXISTS (
    SELECT 1
    FROM GT_TAREA T
    WHERE T.ID_PROYECTO = P.ID_PROYECTO
      AND T.CODIGO = 'PRYGEN_' || TO_CHAR(P.ID_PROYECTO)
);

SELECT
    COUNT(*) AS CONFLICTOS_CODIGO_PRYGEN
FROM GT_TAREA T
WHERE T.CODIGO LIKE 'PRYGEN\_%' ESCAPE '\'
  AND (
        T.ID_PROYECTO IS NULL
        OR T.CODIGO <> 'PRYGEN_' || TO_CHAR(T.ID_PROYECTO)
  );
