-- ATLAS v0.3.0
-- Seguridad de sesión, bloqueo de acceso, auditoría y aprobación semanal.
-- Ejecutar con el esquema propietario de las tablas ATLAS.

SET DEFINE OFF;

BEGIN
    EXECUTE IMMEDIATE q'[
        ALTER TABLE GT_USUARIO_AUTH ADD (
            SESSION_VERSION NUMBER DEFAULT 1 NOT NULL
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        ALTER TABLE GT_USUARIO_AUTH ADD (
            BLOQUEADO_HASTA TIMESTAMP
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

UPDATE GT_USUARIO_AUTH
   SET SESSION_VERSION = NVL(SESSION_VERSION, 1)
 WHERE SESSION_VERSION IS NULL;

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE GT_LOGIN_RATE_LIMIT (
            IP_ORIGEN           VARCHAR2(64 CHAR) NOT NULL,
            INTENTOS_FALLIDOS   NUMBER DEFAULT 0 NOT NULL,
            VENTANA_INICIO      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            BLOQUEADO_HASTA     TIMESTAMP,
            FECHA_ACTUALIZACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_GT_LOGIN_RATE_LIMIT PRIMARY KEY (IP_ORIGEN),
            CONSTRAINT CK_GT_LOGIN_RATE_INT CHECK (INTENTOS_FALLIDOS >= 0)
        ) NOCOMPRESS
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

DECLARE
    V_EXISTS NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_EXISTS
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'GT_VALIDACION_PERIODO'
      AND CONSTRAINT_NAME = 'CK_GT_VAL_ESTADO';
    IF V_EXISTS > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE GT_VALIDACION_PERIODO DROP CONSTRAINT CK_GT_VAL_ESTADO';
    END IF;
END;
/

ALTER TABLE GT_VALIDACION_PERIODO ADD CONSTRAINT CK_GT_VAL_ESTADO CHECK (
    ESTADO IN (
        'PENDIENTE', 'ENVIADO', 'APROBADO',
        'RECHAZADO', 'OBSERVADO', 'REABIERTO', 'CERRADO'
    )
);

DECLARE
    V_EXISTS NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_EXISTS
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'GT_AUDITORIA'
      AND CONSTRAINT_NAME = 'CK_GT_AUD_ACCION';
    IF V_EXISTS > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE GT_AUDITORIA DROP CONSTRAINT CK_GT_AUD_ACCION';
    END IF;
END;
/

ALTER TABLE GT_AUDITORIA MODIFY ACCION VARCHAR2(30 CHAR);

ALTER TABLE GT_AUDITORIA ADD CONSTRAINT CK_GT_AUD_ACCION CHECK (
    ACCION IN (
        'INSERT', 'UPDATE', 'DELETE', 'STATUS',
        'LOGIN', 'LOGOUT', 'RESET_FAILED_ATTEMPTS',
        'GUARDAR_SEMANA', 'ENVIAR', 'APROBAR',
        'OBSERVAR', 'RECHAZAR', 'REABRIR', 'CERRAR'
    )
);

DECLARE
    V_EXISTS NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_EXISTS
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'IX_GT_VAL_ESTADO_ENVIO';
    IF V_EXISTS = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE INDEX IX_GT_VAL_ESTADO_ENVIO
            ON GT_VALIDACION_PERIODO (ESTADO, FECHA_ENVIO, ID_VALIDADOR)
        ]';
    END IF;
END;
/

COMMIT;
