-- Validación posterior a la instalación ATLAS v0.3.0.

SELECT COLUMN_NAME, DATA_TYPE, DATA_DEFAULT, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'GT_USUARIO_AUTH'
  AND COLUMN_NAME IN ('SESSION_VERSION', 'BLOQUEADO_HASTA')
ORDER BY COLUMN_NAME;

SELECT CONSTRAINT_NAME, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('GT_VALIDACION_PERIODO', 'GT_AUDITORIA')
  AND CONSTRAINT_NAME IN ('CK_GT_VAL_ESTADO', 'CK_GT_AUD_ACCION');

SELECT INDEX_NAME, STATUS
FROM USER_INDEXES
WHERE INDEX_NAME = 'IX_GT_VAL_ESTADO_ENVIO';

SELECT
    COUNT(*) AS USUARIOS_AUTH,
    SUM(CASE WHEN SESSION_VERSION >= 1 THEN 1 ELSE 0 END) AS VERSIONADOS,
    SUM(CASE WHEN BLOQUEADO_HASTA > SYSTIMESTAMP THEN 1 ELSE 0 END) AS BLOQUEADOS
FROM GT_USUARIO_AUTH;

SELECT ESTADO, COUNT(*) AS CANTIDAD
FROM GT_VALIDACION_PERIODO
GROUP BY ESTADO
ORDER BY ESTADO;

SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME = 'GT_LOGIN_RATE_LIMIT';

SELECT COUNT(*) AS ORIGENES_BLOQUEADOS
FROM GT_LOGIN_RATE_LIMIT
WHERE BLOQUEADO_HASTA > SYSTIMESTAMP;
