-- ATLAS v0.3.0 - Rollback lógico seguro hacia v0.2.x.
-- No elimina SESSION_VERSION, BLOQUEADO_HASTA ni GT_LOGIN_RATE_LIMIT.
-- Ejecutar solo después de detener la aplicación y restaurar el código v0.2.x.

SET DEFINE OFF;

DECLARE
    V_CERRADOS NUMBER;
    V_AUD_CERRAR NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_CERRADOS
    FROM GT_VALIDACION_PERIODO
    WHERE ESTADO = 'CERRADO';

    SELECT COUNT(*) INTO V_AUD_CERRAR
    FROM GT_AUDITORIA
    WHERE ACCION = 'CERRAR';

    IF V_CERRADOS > 0 OR V_AUD_CERRAR > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20031,
            'Rollback detenido: existen semanas cerradas o auditoría CERRAR. '
            || 'Reabrir/reclasificar de forma controlada antes de continuar.'
        );
    END IF;
END;
/

DECLARE
    V_EXISTS NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_EXISTS
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'GT_VALIDACION_PERIODO'
      AND CONSTRAINT_NAME = 'CK_GT_VAL_ESTADO';
    IF V_EXISTS > 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE GT_VALIDACION_PERIODO DROP CONSTRAINT CK_GT_VAL_ESTADO';
    END IF;
END;
/

ALTER TABLE GT_VALIDACION_PERIODO ADD CONSTRAINT CK_GT_VAL_ESTADO CHECK (
    ESTADO IN (
        'PENDIENTE', 'ENVIADO', 'APROBADO',
        'RECHAZADO', 'OBSERVADO', 'REABIERTO'
    )
);

DECLARE
    V_EXISTS NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_EXISTS
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'GT_AUDITORIA'
      AND CONSTRAINT_NAME = 'CK_GT_AUD_ACCION';
    IF V_EXISTS > 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE GT_AUDITORIA DROP CONSTRAINT CK_GT_AUD_ACCION';
    END IF;
END;
/

ALTER TABLE GT_AUDITORIA ADD CONSTRAINT CK_GT_AUD_ACCION CHECK (
    ACCION IN (
        'INSERT', 'UPDATE', 'DELETE', 'STATUS',
        'LOGIN', 'LOGOUT', 'RESET_FAILED_ATTEMPTS',
        'GUARDAR_SEMANA', 'ENVIAR', 'APROBAR',
        'OBSERVAR', 'RECHAZAR', 'REABRIR'
    )
);

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IX_GT_VAL_ESTADO_ENVIO';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1418 THEN RAISE; END IF;
END;
/

COMMIT;

-- Opcional, fuera del rollback automático y solo con aprobación DBA:
-- DROP TABLE GT_LOGIN_RATE_LIMIT PURGE;
-- ALTER TABLE GT_USUARIO_AUTH DROP COLUMN BLOQUEADO_HASTA;
-- ALTER TABLE GT_USUARIO_AUTH DROP COLUMN SESSION_VERSION;
