-- ATLAS v0.4.0
-- Validacion del modelo de conocimiento. Compatible con DBeaver.

SELECT 'GT_CONOCIMIENTO' OBJETO, COUNT(*) CANTIDAD,
       CASE WHEN COUNT(*) = 1 THEN 'OK' ELSE 'REVISAR' END ESTADO
FROM USER_TABLES WHERE TABLE_NAME='GT_CONOCIMIENTO'
UNION ALL
SELECT 'GT_CONOCIMIENTO_RELACION', COUNT(*), CASE WHEN COUNT(*)=1 THEN 'OK' ELSE 'REVISAR' END
FROM USER_TABLES WHERE TABLE_NAME='GT_CONOCIMIENTO_RELACION'
UNION ALL
SELECT 'GT_CONOCIMIENTO_VERSION', COUNT(*), CASE WHEN COUNT(*)=1 THEN 'OK' ELSE 'REVISAR' END
FROM USER_TABLES WHERE TABLE_NAME='GT_CONOCIMIENTO_VERSION'
UNION ALL
SELECT 'GT_CONOCIMIENTO_ARCHIVO', COUNT(*), CASE WHEN COUNT(*)=1 THEN 'OK' ELSE 'REVISAR' END
FROM USER_TABLES WHERE TABLE_NAME='GT_CONOCIMIENTO_ARCHIVO';

SELECT TABLE_NAME, CONSTRAINT_TYPE, COUNT(*) CANTIDAD
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN (
    'GT_CONOCIMIENTO','GT_CONOCIMIENTO_RELACION',
    'GT_CONOCIMIENTO_VERSION','GT_CONOCIMIENTO_ARCHIVO'
)
GROUP BY TABLE_NAME, CONSTRAINT_TYPE
ORDER BY TABLE_NAME, CONSTRAINT_TYPE;

SELECT INDEX_NAME, TABLE_NAME, STATUS
FROM USER_INDEXES
WHERE INDEX_NAME IN (
    'IX_GT_CON_UNIDAD_EST','IX_GT_CON_PROP_EST','IX_GT_CON_REV_EST',
    'IX_GT_CON_REL_ENT','IX_GT_CON_ARCH_CON'
)
ORDER BY INDEX_NAME;

SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME LIKE 'GT\_CONOCIMIENTO%' ESCAPE '\'
  AND STATUS <> 'VALID'
ORDER BY OBJECT_TYPE, OBJECT_NAME;

SELECT NAME, TYPE, LINE, POSITION, TEXT
FROM USER_ERRORS
WHERE NAME LIKE 'GT\_CONOCIMIENTO%' ESCAPE '\'
ORDER BY NAME, TYPE, SEQUENCE;
