-- ATLAS v0.4.0
-- Rollback destructivo SOLO para ambientes de desarrollo/prueba.
-- Elimina exclusivamente los objetos del modulo de conocimiento.
-- Ejecutar con DBeaver / Execute SQL Script.

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE GT_CONOCIMIENTO_ARCHIVO CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE GT_CONOCIMIENTO_RELACION CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE GT_CONOCIMIENTO_VERSION CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE GT_CONOCIMIENTO CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
